package com.javaweb.examenjavav2.POJOS;
// Generated Jul 3, 2018 12:12:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estadocivil generated by hbm2java
 */
public class Estadocivil  implements java.io.Serializable {


     private int estadocivilId;
     private String estadocivilTipo;
     private Set postulantes = new HashSet(0);

    public Estadocivil() {
    }

	
    public Estadocivil(int estadocivilId, String estadocivilTipo) {
        this.estadocivilId = estadocivilId;
        this.estadocivilTipo = estadocivilTipo;
    }
    public Estadocivil(int estadocivilId, String estadocivilTipo, Set postulantes) {
       this.estadocivilId = estadocivilId;
       this.estadocivilTipo = estadocivilTipo;
       this.postulantes = postulantes;
    }
   
    public int getEstadocivilId() {
        return this.estadocivilId;
    }
    
    public void setEstadocivilId(int estadocivilId) {
        this.estadocivilId = estadocivilId;
    }
    public String getEstadocivilTipo() {
        return this.estadocivilTipo;
    }
    
    public void setEstadocivilTipo(String estadocivilTipo) {
        this.estadocivilTipo = estadocivilTipo;
    }
    public Set getPostulantes() {
        return this.postulantes;
    }
    
    public void setPostulantes(Set postulantes) {
        this.postulantes = postulantes;
    }




}


