package com.javaweb.examenjavav2.POJOS;
// Generated Jul 3, 2018 12:12:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Postulante generated by hbm2java
 */
public class Postulante  implements java.io.Serializable {


     private String postulanteRut;
     private Comuna comuna;
     private Educacion educacion;
     private Estadocivil estadocivil;
     private Renta renta;
     private Usuario usuario;
     private char postulanteDv;
     private String postulanteNombre;
     private String postulanteApepa;
     private String postulanteApema;
     private Date postulanteFecnac;
     private char postulanteSexo;
     private int postulanteHijos;
     private int postulanteTelefono;
     private String postulanteEmail;
     private String postulanteDireccion;
     private int postulanteSueldo;
     private char postulanteEnfermedad;

    public Postulante() {
    }

	
    public Postulante(String postulanteRut, Comuna comuna, Educacion educacion, Estadocivil estadocivil, Renta renta, Usuario usuario, char postulanteDv, String postulanteApepa, String postulanteApema, Date postulanteFecnac, char postulanteSexo, int postulanteHijos, int postulanteTelefono, String postulanteEmail, String postulanteDireccion, int postulanteSueldo, char postulanteEnfermedad) {
        this.postulanteRut = postulanteRut;
        this.comuna = comuna;
        this.educacion = educacion;
        this.estadocivil = estadocivil;
        this.renta = renta;
        this.usuario = usuario;
        this.postulanteDv = postulanteDv;
        this.postulanteApepa = postulanteApepa;
        this.postulanteApema = postulanteApema;
        this.postulanteFecnac = postulanteFecnac;
        this.postulanteSexo = postulanteSexo;
        this.postulanteHijos = postulanteHijos;
        this.postulanteTelefono = postulanteTelefono;
        this.postulanteEmail = postulanteEmail;
        this.postulanteDireccion = postulanteDireccion;
        this.postulanteSueldo = postulanteSueldo;
        this.postulanteEnfermedad = postulanteEnfermedad;
    }
    public Postulante(String postulanteRut, Comuna comuna, Educacion educacion, Estadocivil estadocivil, Renta renta, Usuario usuario, char postulanteDv, String postulanteNombre, String postulanteApepa, String postulanteApema, Date postulanteFecnac, char postulanteSexo, int postulanteHijos, int postulanteTelefono, String postulanteEmail, String postulanteDireccion, int postulanteSueldo, char postulanteEnfermedad) {
       this.postulanteRut = postulanteRut;
       this.comuna = comuna;
       this.educacion = educacion;
       this.estadocivil = estadocivil;
       this.renta = renta;
       this.usuario = usuario;
       this.postulanteDv = postulanteDv;
       this.postulanteNombre = postulanteNombre;
       this.postulanteApepa = postulanteApepa;
       this.postulanteApema = postulanteApema;
       this.postulanteFecnac = postulanteFecnac;
       this.postulanteSexo = postulanteSexo;
       this.postulanteHijos = postulanteHijos;
       this.postulanteTelefono = postulanteTelefono;
       this.postulanteEmail = postulanteEmail;
       this.postulanteDireccion = postulanteDireccion;
       this.postulanteSueldo = postulanteSueldo;
       this.postulanteEnfermedad = postulanteEnfermedad;
    }
   
    public String getPostulanteRut() {
        return this.postulanteRut;
    }
    
    public void setPostulanteRut(String postulanteRut) {
        this.postulanteRut = postulanteRut;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public Educacion getEducacion() {
        return this.educacion;
    }
    
    public void setEducacion(Educacion educacion) {
        this.educacion = educacion;
    }
    public Estadocivil getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(Estadocivil estadocivil) {
        this.estadocivil = estadocivil;
    }
    public Renta getRenta() {
        return this.renta;
    }
    
    public void setRenta(Renta renta) {
        this.renta = renta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public char getPostulanteDv() {
        return this.postulanteDv;
    }
    
    public void setPostulanteDv(char postulanteDv) {
        this.postulanteDv = postulanteDv;
    }
    public String getPostulanteNombre() {
        return this.postulanteNombre;
    }
    
    public void setPostulanteNombre(String postulanteNombre) {
        this.postulanteNombre = postulanteNombre;
    }
    public String getPostulanteApepa() {
        return this.postulanteApepa;
    }
    
    public void setPostulanteApepa(String postulanteApepa) {
        this.postulanteApepa = postulanteApepa;
    }
    public String getPostulanteApema() {
        return this.postulanteApema;
    }
    
    public void setPostulanteApema(String postulanteApema) {
        this.postulanteApema = postulanteApema;
    }
    public Date getPostulanteFecnac() {
        return this.postulanteFecnac;
    }
    
    public void setPostulanteFecnac(Date postulanteFecnac) {
        this.postulanteFecnac = postulanteFecnac;
    }
    public char getPostulanteSexo() {
        return this.postulanteSexo;
    }
    
    public void setPostulanteSexo(char postulanteSexo) {
        this.postulanteSexo = postulanteSexo;
    }
    public int getPostulanteHijos() {
        return this.postulanteHijos;
    }
    
    public void setPostulanteHijos(int postulanteHijos) {
        this.postulanteHijos = postulanteHijos;
    }
    public int getPostulanteTelefono() {
        return this.postulanteTelefono;
    }
    
    public void setPostulanteTelefono(int postulanteTelefono) {
        this.postulanteTelefono = postulanteTelefono;
    }
    public String getPostulanteEmail() {
        return this.postulanteEmail;
    }
    
    public void setPostulanteEmail(String postulanteEmail) {
        this.postulanteEmail = postulanteEmail;
    }
    public String getPostulanteDireccion() {
        return this.postulanteDireccion;
    }
    
    public void setPostulanteDireccion(String postulanteDireccion) {
        this.postulanteDireccion = postulanteDireccion;
    }
    public int getPostulanteSueldo() {
        return this.postulanteSueldo;
    }
    
    public void setPostulanteSueldo(int postulanteSueldo) {
        this.postulanteSueldo = postulanteSueldo;
    }
    public char getPostulanteEnfermedad() {
        return this.postulanteEnfermedad;
    }
    
    public void setPostulanteEnfermedad(char postulanteEnfermedad) {
        this.postulanteEnfermedad = postulanteEnfermedad;
    }




}


