package com.javaweb.examenjavav2.POJOS;
// Generated Jun 26, 2018 12:16:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Renta generated by hbm2java
 */
public class Renta  implements java.io.Serializable {


     private int rentaId;
     private String rentaTipo;
     private Set postulantes = new HashSet(0);

    public Renta() {
    }

	
    public Renta(int rentaId, String rentaTipo) {
        this.rentaId = rentaId;
        this.rentaTipo = rentaTipo;
    }
    public Renta(int rentaId, String rentaTipo, Set postulantes) {
       this.rentaId = rentaId;
       this.rentaTipo = rentaTipo;
       this.postulantes = postulantes;
    }
   
    public int getRentaId() {
        return this.rentaId;
    }
    
    public void setRentaId(int rentaId) {
        this.rentaId = rentaId;
    }
    public String getRentaTipo() {
        return this.rentaTipo;
    }
    
    public void setRentaTipo(String rentaTipo) {
        this.rentaTipo = rentaTipo;
    }
    public Set getPostulantes() {
        return this.postulantes;
    }
    
    public void setPostulantes(Set postulantes) {
        this.postulantes = postulantes;
    }




}


