package com.javaweb.examenjavav2.POJOS;
// Generated Jul 3, 2018 12:12:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuarioId;
     private String usuarioNombre;
     private String usuarioPass;
     private char usuarioRoladm;
     private Set postulantes = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    public Usuario(String usuarioNombre, String usuarioPass){
        this.usuarioNombre = usuarioNombre;
        this.usuarioPass = usuarioPass;
    }
    
    public Usuario(String usuarioNombre, String usuarioPass, boolean isAdmin){
        this.usuarioNombre = usuarioNombre;
        this.usuarioPass = usuarioPass;
        this.usuarioRoladm = isAdmin ? 's' : 'n';
    }
	
    public Usuario(String usuarioNombre, String usuarioPass, char usuarioRoladm) {
        this.usuarioNombre = usuarioNombre;
        this.usuarioPass = usuarioPass;
        this.usuarioRoladm = usuarioRoladm;
    }
    public Usuario(String usuarioNombre, String usuarioPass, char usuarioRoladm, Set postulantes) {
       this.usuarioNombre = usuarioNombre;
       this.usuarioPass = usuarioPass;
       this.usuarioRoladm = usuarioRoladm;
       this.postulantes = postulantes;
    }
   
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioPass() {
        return this.usuarioPass;
    }
    
    public void setUsuarioPass(String usuarioPass) {
        this.usuarioPass = usuarioPass;
    }
    public char getUsuarioRoladm() {
        return this.usuarioRoladm;
    }
    
    public void setUsuarioRoladm(char usuarioRoladm) {
        this.usuarioRoladm = usuarioRoladm;
    }
    public Set getPostulantes() {
        return this.postulantes;
    }
    
    public void setPostulantes(Set postulantes) {
        this.postulantes = postulantes;
    }




}


